config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :articles
  

  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5, maximum: 150}
	has_many :comments
end 

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :get_article, only: [:show, :edit, :update, :destroy]

	def fancy_method
		
	end


	def index
		@elephants = Article.all
	end
	def new 
		@article = Article.new
	end

	def edit
	end

	def create 
		@article = Article.new(articles_params)
		if @article.save
		redirect_to @article, notice: "Your article was successfully created."
	else
	render :new 
	end 
end

	def update
		if @article.update(articles_params)
		redirect_to @article
		else
			render :edit
		end
	end

	def show
	end		

	def destroy
		@article.delete
		redirect_to articles_path 
end
	private

	def get_article
	@article = Article.find(params[:id])
end

	def articles_params
		params.require(:article).permit(:title, :content)
	end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :name, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<div id="error explanation">
	<h2>
	<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
	</h2>
	<ul>
		<%= @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>


<%= form_for :article, url: articles_path do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<br>
	<%= f.label :content %><br>
	<%= f.text_area :content %>
	<br>
	<%= f.submit %>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Articles</h1>
<% if @article.errors.any? %>
<div id="error explanation">
	<h2>
	<%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
	</h2>
	<ul>
		<%= @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>


<%= form_for :article, url: articles_path do |f| %>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
	<br>
	<%= f.label :content %><br>
	<%= f.text_area :content %>
	<br>
	<%= f.submit "Update" %>

<% end %>
<br>
<%= link_to "Cancel", articles_path %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<table>
	<tr>
		<td>ID</td>
		<td>Title</td>
		<td>Created at</td>
		<td></td>
		<td></td>
	</tr>

<% @elephants.each do |article| %>
<tr>
	<td><%= article.id %></td>
	<td><%= link_to article.title, article_path(article) %></td>
	<td><%= article.created_at %></td>
	<td><%= link_to "Edit", edit_article_path(article) %></td>
	<td><%= link_to "Delete", article, method: :delete %></td>
</tr>
<% end %>
</table>

<br>
<%= link_to "New article", new_article_path %>
<br>
<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<br>
<%= link_to "Cancel", articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>

<%= link_to "Return to New Articles", articles_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :articles_id %><br>
    <%= f.text_field :articles_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Articles</th>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article %></td>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Articles:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h1>Welcome to my magazine</h1>
<p>Best articles ever</p>

<%= link_to  "see a list of the articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Magazineapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>